apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "taskset -c 0 ./memcached -t 1 -u memcache"]
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1"
        limits:
          memory: "1024Mi"
          cpu: "1"
  nodeSelector:
    cca-project-nodetype: "node-b-2core"


