apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "taskset -c 0 ./memcached -t 1 -u memcache"]
      # Whether to use resource requests and limits
      # depends on the node type
      #resources:
      #  requests:
      #    memory: "512Mi"
      #    cpu: "900m"  # Nearly 1 full core
      #  limits:
      #    memory: "1Gi"
      #    cpu: "1"     # 1 full core
  nodeSelector:
    cca-project-nodetype: "node-b-2core"


