all:
  children:
    memcached_servers:
      hosts:
        memcache-server:
          internal_ip: 10.0.16.3 # internal IP of memcache-server
          memcached_threads: 1
    client_agents:
      hosts:
        client-agent:
          ansible_host: 35.205.217.105 # external IP of client-agent
          internal_ip: 10.0.16.4 # internal IP of client-agent
    client_measures:
      hosts:
        client-measure:
          ansible_host: 34.38.114.123 # external IP of client-measure
          internal_ip: 10.0.16.5 # internal IP of client-measure
  vars: # replace with the command you want to run
    mcperf_command: "./mcperf -s {{ memcached_server_ip }} -a {{ agent_server_ip }} --noload -T 8 -C 8 -D 4 -Q 1000 -c 8 -t 5 --scan 5000:220000:5000"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/cloud-computing
